{% set name = "fishersapi" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fishersapi-{{ version }}.tar.gz
  sha256: d1c294e00376d6af3f9f98a51b1425546717cd85ef7f66da96ba608a56460df4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - fisher
    - numpy
    - pandas
    - python
    - scipy
    - statsmodels

test:
  imports:
    - fishersapi
    - fishersapi.tests

about:
  home: http://github.com/agartland/fishersapi
  summary: "fishersapi: An API for applying a fast Fisher's Exact Test to variable pairs in pandas DataFrames"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knutwa-ext
