{% set name = "fishersapi" %}
{% set version = "0.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fishersapi-{{ version }}.tar.gz
  sha256: e15e6aed5ce2e59b40ae757726aa6903eaf4a05732fa1fdee0a43d848d5b9b0d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - fisher
    - numpy
    - pandas
    - python
    - scipy
    - statsmodels

test:
  imports:
    - fishersapi
    - fishersapi.tests

about:
  home: http://github.com/agartland/fishersapi
  summary: "fishersapi: An API for applying a fast Fisher's Exact Test to variable pairs in pandas DataFrames"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knutwa-ext
