{% set name = "fishersapi" %}
{% set version = "0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fishersapi-{{ version }}.tar.gz
  sha256: bea62be8af207e56e7d4aa574e00015a4085ffc0bc9c2c5cfd347d4110d8297e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - fisher
    - numpy
    - pandas
    - python
    - scipy
    - statsmodels

test:
  imports:
    - fishersapi
    - fishersapi.tests

about:
  home: http://github.com/agartland/fishersapi
  summary: "fishersapi: An API for applying a fast Fisher's Exact Test to variable pairs in pandas DataFrames"
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - knutwa-ext
